// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: dynamo.proto

package dynamo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------
// node identity
// ------------------------------------------------------------
type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // e.g., "node-1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_dynamo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{0}
}

func (x *NodeID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ------------------------------------------------------------
// Vector Clock
// ------------------------------------------------------------
type VectorClockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Counter       int64                  `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClockEntry) Reset() {
	*x = VectorClockEntry{}
	mi := &file_dynamo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClockEntry) ProtoMessage() {}

func (x *VectorClockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClockEntry.ProtoReflect.Descriptor instead.
func (*VectorClockEntry) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{1}
}

func (x *VectorClockEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VectorClockEntry) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*VectorClockEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_dynamo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{2}
}

func (x *VectorClock) GetEntries() []*VectorClockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ------------------------------------------------------------
// Versioned Value (Dynamo Core)
// ------------------------------------------------------------
type VersionedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Clock         *VectorClock           `protobuf:"bytes,2,opt,name=clock,proto3" json:"clock,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // optional, for LWW fallback
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedValue) Reset() {
	*x = VersionedValue{}
	mi := &file_dynamo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedValue) ProtoMessage() {}

func (x *VersionedValue) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedValue.ProtoReflect.Descriptor instead.
func (*VersionedValue) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{3}
}

func (x *VersionedValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *VersionedValue) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *VersionedValue) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Coordinator → Replica
type InternalPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          *VersionedValue        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsHint        bool                   `protobuf:"varint,3,opt,name=is_hint,json=isHint,proto3" json:"is_hint,omitempty"`                  // true if this is hinted handoff
	OriginalNode  string                 `protobuf:"bytes,4,opt,name=original_node,json=originalNode,proto3" json:"original_node,omitempty"` // original target of hint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalPutRequest) Reset() {
	*x = InternalPutRequest{}
	mi := &file_dynamo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalPutRequest) ProtoMessage() {}

func (x *InternalPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalPutRequest.ProtoReflect.Descriptor instead.
func (*InternalPutRequest) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{4}
}

func (x *InternalPutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *InternalPutRequest) GetData() *VersionedValue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InternalPutRequest) GetIsHint() bool {
	if x != nil {
		return x.IsHint
	}
	return false
}

func (x *InternalPutRequest) GetOriginalNode() string {
	if x != nil {
		return x.OriginalNode
	}
	return ""
}

type InternalPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalPutResponse) Reset() {
	*x = InternalPutResponse{}
	mi := &file_dynamo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalPutResponse) ProtoMessage() {}

func (x *InternalPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalPutResponse.ProtoReflect.Descriptor instead.
func (*InternalPutResponse) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{5}
}

func (x *InternalPutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Coordinator → Replica
type InternalGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalGetRequest) Reset() {
	*x = InternalGetRequest{}
	mi := &file_dynamo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalGetRequest) ProtoMessage() {}

func (x *InternalGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalGetRequest.ProtoReflect.Descriptor instead.
func (*InternalGetRequest) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{6}
}

func (x *InternalGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type InternalGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*VersionedValue      `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalGetResponse) Reset() {
	*x = InternalGetResponse{}
	mi := &file_dynamo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalGetResponse) ProtoMessage() {}

func (x *InternalGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalGetResponse.ProtoReflect.Descriptor instead.
func (*InternalGetResponse) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{7}
}

func (x *InternalGetResponse) GetVersions() []*VersionedValue {
	if x != nil {
		return x.Versions
	}
	return nil
}

// ------------------------------------------------------------
// Sloppy Quorum + Hinted Handoff metadata exchange
// ------------------------------------------------------------
type Hint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          *VersionedValue        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TargetNode    string                 `protobuf:"bytes,3,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hint) Reset() {
	*x = Hint{}
	mi := &file_dynamo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hint) ProtoMessage() {}

func (x *Hint) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hint.ProtoReflect.Descriptor instead.
func (*Hint) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{8}
}

func (x *Hint) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Hint) GetData() *VersionedValue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Hint) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type HandoffBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hints         []*Hint                `protobuf:"bytes,1,rep,name=hints,proto3" json:"hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandoffBatch) Reset() {
	*x = HandoffBatch{}
	mi := &file_dynamo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandoffBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandoffBatch) ProtoMessage() {}

func (x *HandoffBatch) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandoffBatch.ProtoReflect.Descriptor instead.
func (*HandoffBatch) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{9}
}

func (x *HandoffBatch) GetHints() []*Hint {
	if x != nil {
		return x.Hints
	}
	return nil
}

type HandoffAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandoffAck) Reset() {
	*x = HandoffAck{}
	mi := &file_dynamo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandoffAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandoffAck) ProtoMessage() {}

func (x *HandoffAck) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandoffAck.ProtoReflect.Descriptor instead.
func (*HandoffAck) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{10}
}

func (x *HandoffAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FetchHintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNode    string                 `protobuf:"bytes,1,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchHintsRequest) Reset() {
	*x = FetchHintsRequest{}
	mi := &file_dynamo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchHintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHintsRequest) ProtoMessage() {}

func (x *FetchHintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHintsRequest.ProtoReflect.Descriptor instead.
func (*FetchHintsRequest) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{11}
}

func (x *FetchHintsRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

// ------------------------------------------------------------
// Metadata Sync for Gossip
// ------------------------------------------------------------
type NodeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Alive         bool                   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	Heartbeat     int64                  `protobuf:"varint,3,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_dynamo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{12}
}

func (x *NodeState) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeState) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *NodeState) GetHeartbeat() int64 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

type GossipState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeState           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipState) Reset() {
	*x = GossipState{}
	mi := &file_dynamo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipState) ProtoMessage() {}

func (x *GossipState) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipState.ProtoReflect.Descriptor instead.
func (*GossipState) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{13}
}

func (x *GossipState) GetNodes() []*NodeState {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_dynamo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{14}
}

func (x *GossipResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_dynamo_proto protoreflect.FileDescriptor

const file_dynamo_proto_rawDesc = "" +
	"\n" +
	"\fdynamo.proto\x12\x06dynamo\"\x18\n" +
	"\x06NodeID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x10VectorClockEntry\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x03R\acounter\"A\n" +
	"\vVectorClock\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.dynamo.VectorClockEntryR\aentries\"o\n" +
	"\x0eVersionedValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12)\n" +
	"\x05clock\x18\x02 \x01(\v2\x13.dynamo.VectorClockR\x05clock\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x90\x01\n" +
	"\x12InternalPutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.dynamo.VersionedValueR\x04data\x12\x17\n" +
	"\ais_hint\x18\x03 \x01(\bR\x06isHint\x12#\n" +
	"\roriginal_node\x18\x04 \x01(\tR\foriginalNode\"%\n" +
	"\x13InternalPutResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"&\n" +
	"\x12InternalGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"I\n" +
	"\x13InternalGetResponse\x122\n" +
	"\bversions\x18\x01 \x03(\v2\x16.dynamo.VersionedValueR\bversions\"e\n" +
	"\x04Hint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.dynamo.VersionedValueR\x04data\x12\x1f\n" +
	"\vtarget_node\x18\x03 \x01(\tR\n" +
	"targetNode\"2\n" +
	"\fHandoffBatch\x12\"\n" +
	"\x05hints\x18\x01 \x03(\v2\f.dynamo.HintR\x05hints\"\x1c\n" +
	"\n" +
	"HandoffAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"4\n" +
	"\x11FetchHintsRequest\x12\x1f\n" +
	"\vtarget_node\x18\x01 \x01(\tR\n" +
	"targetNode\"S\n" +
	"\tNodeState\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive\x12\x1c\n" +
	"\theartbeat\x18\x03 \x01(\x03R\theartbeat\"6\n" +
	"\vGossipState\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.dynamo.NodeStateR\x05nodes\" \n" +
	"\x0eGossipResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xcc\x02\n" +
	"\tDynamoRPC\x12F\n" +
	"\vInternalPut\x12\x1a.dynamo.InternalPutRequest\x1a\x1b.dynamo.InternalPutResponse\x12F\n" +
	"\vInternalGet\x12\x1a.dynamo.InternalGetRequest\x1a\x1b.dynamo.InternalGetResponse\x125\n" +
	"\tSendHints\x12\x14.dynamo.HandoffBatch\x1a\x12.dynamo.HandoffAck\x129\n" +
	"\n" +
	"PushGossip\x12\x13.dynamo.GossipState\x1a\x16.dynamo.GossipResponse\x12=\n" +
	"\n" +
	"FetchHints\x12\x19.dynamo.FetchHintsRequest\x1a\x14.dynamo.HandoffBatchB:Z8github.com/llllleeeewwwiis/distributed_core/proto/dynamob\x06proto3"

var (
	file_dynamo_proto_rawDescOnce sync.Once
	file_dynamo_proto_rawDescData []byte
)

func file_dynamo_proto_rawDescGZIP() []byte {
	file_dynamo_proto_rawDescOnce.Do(func() {
		file_dynamo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamo_proto_rawDesc), len(file_dynamo_proto_rawDesc)))
	})
	return file_dynamo_proto_rawDescData
}

var file_dynamo_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_dynamo_proto_goTypes = []any{
	(*NodeID)(nil),              // 0: dynamo.NodeID
	(*VectorClockEntry)(nil),    // 1: dynamo.VectorClockEntry
	(*VectorClock)(nil),         // 2: dynamo.VectorClock
	(*VersionedValue)(nil),      // 3: dynamo.VersionedValue
	(*InternalPutRequest)(nil),  // 4: dynamo.InternalPutRequest
	(*InternalPutResponse)(nil), // 5: dynamo.InternalPutResponse
	(*InternalGetRequest)(nil),  // 6: dynamo.InternalGetRequest
	(*InternalGetResponse)(nil), // 7: dynamo.InternalGetResponse
	(*Hint)(nil),                // 8: dynamo.Hint
	(*HandoffBatch)(nil),        // 9: dynamo.HandoffBatch
	(*HandoffAck)(nil),          // 10: dynamo.HandoffAck
	(*FetchHintsRequest)(nil),   // 11: dynamo.FetchHintsRequest
	(*NodeState)(nil),           // 12: dynamo.NodeState
	(*GossipState)(nil),         // 13: dynamo.GossipState
	(*GossipResponse)(nil),      // 14: dynamo.GossipResponse
}
var file_dynamo_proto_depIdxs = []int32{
	1,  // 0: dynamo.VectorClock.entries:type_name -> dynamo.VectorClockEntry
	2,  // 1: dynamo.VersionedValue.clock:type_name -> dynamo.VectorClock
	3,  // 2: dynamo.InternalPutRequest.data:type_name -> dynamo.VersionedValue
	3,  // 3: dynamo.InternalGetResponse.versions:type_name -> dynamo.VersionedValue
	3,  // 4: dynamo.Hint.data:type_name -> dynamo.VersionedValue
	8,  // 5: dynamo.HandoffBatch.hints:type_name -> dynamo.Hint
	12, // 6: dynamo.GossipState.nodes:type_name -> dynamo.NodeState
	4,  // 7: dynamo.DynamoRPC.InternalPut:input_type -> dynamo.InternalPutRequest
	6,  // 8: dynamo.DynamoRPC.InternalGet:input_type -> dynamo.InternalGetRequest
	9,  // 9: dynamo.DynamoRPC.SendHints:input_type -> dynamo.HandoffBatch
	13, // 10: dynamo.DynamoRPC.PushGossip:input_type -> dynamo.GossipState
	11, // 11: dynamo.DynamoRPC.FetchHints:input_type -> dynamo.FetchHintsRequest
	5,  // 12: dynamo.DynamoRPC.InternalPut:output_type -> dynamo.InternalPutResponse
	7,  // 13: dynamo.DynamoRPC.InternalGet:output_type -> dynamo.InternalGetResponse
	10, // 14: dynamo.DynamoRPC.SendHints:output_type -> dynamo.HandoffAck
	14, // 15: dynamo.DynamoRPC.PushGossip:output_type -> dynamo.GossipResponse
	9,  // 16: dynamo.DynamoRPC.FetchHints:output_type -> dynamo.HandoffBatch
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dynamo_proto_init() }
func file_dynamo_proto_init() {
	if File_dynamo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamo_proto_rawDesc), len(file_dynamo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dynamo_proto_goTypes,
		DependencyIndexes: file_dynamo_proto_depIdxs,
		MessageInfos:      file_dynamo_proto_msgTypes,
	}.Build()
	File_dynamo_proto = out.File
	file_dynamo_proto_goTypes = nil
	file_dynamo_proto_depIdxs = nil
}
