// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: dynamo.proto

package dynamo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynamoRPC_InternalPut_FullMethodName = "/dynamo.DynamoRPC/InternalPut"
	DynamoRPC_InternalGet_FullMethodName = "/dynamo.DynamoRPC/InternalGet"
	DynamoRPC_SendHints_FullMethodName   = "/dynamo.DynamoRPC/SendHints"
	DynamoRPC_PushGossip_FullMethodName  = "/dynamo.DynamoRPC/PushGossip"
)

// DynamoRPCClient is the client API for DynamoRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------------------------------------------------------------
// Dynamo Internal RPC Service
// ------------------------------------------------------------
type DynamoRPCClient interface {
	// Replication API
	InternalPut(ctx context.Context, in *InternalPutRequest, opts ...grpc.CallOption) (*InternalPutResponse, error)
	InternalGet(ctx context.Context, in *InternalGetRequest, opts ...grpc.CallOption) (*InternalGetResponse, error)
	// Hinted handoff
	SendHints(ctx context.Context, in *HandoffBatch, opts ...grpc.CallOption) (*HandoffAck, error)
	// Gossip membership
	PushGossip(ctx context.Context, in *GossipState, opts ...grpc.CallOption) (*GossipResponse, error)
}

type dynamoRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamoRPCClient(cc grpc.ClientConnInterface) DynamoRPCClient {
	return &dynamoRPCClient{cc}
}

func (c *dynamoRPCClient) InternalPut(ctx context.Context, in *InternalPutRequest, opts ...grpc.CallOption) (*InternalPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalPutResponse)
	err := c.cc.Invoke(ctx, DynamoRPC_InternalPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoRPCClient) InternalGet(ctx context.Context, in *InternalGetRequest, opts ...grpc.CallOption) (*InternalGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalGetResponse)
	err := c.cc.Invoke(ctx, DynamoRPC_InternalGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoRPCClient) SendHints(ctx context.Context, in *HandoffBatch, opts ...grpc.CallOption) (*HandoffAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandoffAck)
	err := c.cc.Invoke(ctx, DynamoRPC_SendHints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoRPCClient) PushGossip(ctx context.Context, in *GossipState, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, DynamoRPC_PushGossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamoRPCServer is the server API for DynamoRPC service.
// All implementations must embed UnimplementedDynamoRPCServer
// for forward compatibility.
//
// ------------------------------------------------------------
// Dynamo Internal RPC Service
// ------------------------------------------------------------
type DynamoRPCServer interface {
	// Replication API
	InternalPut(context.Context, *InternalPutRequest) (*InternalPutResponse, error)
	InternalGet(context.Context, *InternalGetRequest) (*InternalGetResponse, error)
	// Hinted handoff
	SendHints(context.Context, *HandoffBatch) (*HandoffAck, error)
	// Gossip membership
	PushGossip(context.Context, *GossipState) (*GossipResponse, error)
	mustEmbedUnimplementedDynamoRPCServer()
}

// UnimplementedDynamoRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamoRPCServer struct{}

func (UnimplementedDynamoRPCServer) InternalPut(context.Context, *InternalPutRequest) (*InternalPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalPut not implemented")
}
func (UnimplementedDynamoRPCServer) InternalGet(context.Context, *InternalGetRequest) (*InternalGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalGet not implemented")
}
func (UnimplementedDynamoRPCServer) SendHints(context.Context, *HandoffBatch) (*HandoffAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHints not implemented")
}
func (UnimplementedDynamoRPCServer) PushGossip(context.Context, *GossipState) (*GossipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushGossip not implemented")
}
func (UnimplementedDynamoRPCServer) mustEmbedUnimplementedDynamoRPCServer() {}
func (UnimplementedDynamoRPCServer) testEmbeddedByValue()                   {}

// UnsafeDynamoRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamoRPCServer will
// result in compilation errors.
type UnsafeDynamoRPCServer interface {
	mustEmbedUnimplementedDynamoRPCServer()
}

func RegisterDynamoRPCServer(s grpc.ServiceRegistrar, srv DynamoRPCServer) {
	// If the following call pancis, it indicates UnimplementedDynamoRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynamoRPC_ServiceDesc, srv)
}

func _DynamoRPC_InternalPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoRPCServer).InternalPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoRPC_InternalPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoRPCServer).InternalPut(ctx, req.(*InternalPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoRPC_InternalGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoRPCServer).InternalGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoRPC_InternalGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoRPCServer).InternalGet(ctx, req.(*InternalGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoRPC_SendHints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandoffBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoRPCServer).SendHints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoRPC_SendHints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoRPCServer).SendHints(ctx, req.(*HandoffBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoRPC_PushGossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoRPCServer).PushGossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoRPC_PushGossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoRPCServer).PushGossip(ctx, req.(*GossipState))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamoRPC_ServiceDesc is the grpc.ServiceDesc for DynamoRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamoRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamo.DynamoRPC",
	HandlerType: (*DynamoRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalPut",
			Handler:    _DynamoRPC_InternalPut_Handler,
		},
		{
			MethodName: "InternalGet",
			Handler:    _DynamoRPC_InternalGet_Handler,
		},
		{
			MethodName: "SendHints",
			Handler:    _DynamoRPC_SendHints_Handler,
		},
		{
			MethodName: "PushGossip",
			Handler:    _DynamoRPC_PushGossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dynamo.proto",
}
