// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rawkv.proto

package rawkv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cf            string                 `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawGetRequest) Reset() {
	*x = RawGetRequest{}
	mi := &file_rawkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGetRequest) ProtoMessage() {}

func (x *RawGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGetRequest.ProtoReflect.Descriptor instead.
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{0}
}

func (x *RawGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawGetRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

type RawGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	NotFound      bool                   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawGetResponse) Reset() {
	*x = RawGetResponse{}
	mi := &file_rawkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGetResponse) ProtoMessage() {}

func (x *RawGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGetResponse.ProtoReflect.Descriptor instead.
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{1}
}

func (x *RawGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RawGetResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

type RawPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Cf            string                 `protobuf:"bytes,3,opt,name=cf,proto3" json:"cf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPutRequest) Reset() {
	*x = RawPutRequest{}
	mi := &file_rawkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPutRequest) ProtoMessage() {}

func (x *RawPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPutRequest.ProtoReflect.Descriptor instead.
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{2}
}

func (x *RawPutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RawPutRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

type RawPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPutResponse) Reset() {
	*x = RawPutResponse{}
	mi := &file_rawkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPutResponse) ProtoMessage() {}

func (x *RawPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPutResponse.ProtoReflect.Descriptor instead.
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{3}
}

type RawDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cf            string                 `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawDeleteRequest) Reset() {
	*x = RawDeleteRequest{}
	mi := &file_rawkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDeleteRequest) ProtoMessage() {}

func (x *RawDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDeleteRequest.ProtoReflect.Descriptor instead.
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{4}
}

func (x *RawDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawDeleteRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

type RawDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawDeleteResponse) Reset() {
	*x = RawDeleteResponse{}
	mi := &file_rawkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDeleteResponse) ProtoMessage() {}

func (x *RawDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDeleteResponse.ProtoReflect.Descriptor instead.
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{5}
}

type RawScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cf            string                 `protobuf:"bytes,3,opt,name=cf,proto3" json:"cf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawScanRequest) Reset() {
	*x = RawScanRequest{}
	mi := &file_rawkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawScanRequest) ProtoMessage() {}

func (x *RawScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawScanRequest.ProtoReflect.Descriptor instead.
func (*RawScanRequest) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{6}
}

func (x *RawScanRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RawScanRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RawScanRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

type KvPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvPair) Reset() {
	*x = KvPair{}
	mi := &file_rawkv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPair) ProtoMessage() {}

func (x *KvPair) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPair.ProtoReflect.Descriptor instead.
func (*KvPair) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{7}
}

func (x *KvPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KvPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RawScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           []*KvPair              `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawScanResponse) Reset() {
	*x = RawScanResponse{}
	mi := &file_rawkv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawScanResponse) ProtoMessage() {}

func (x *RawScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rawkv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawScanResponse.ProtoReflect.Descriptor instead.
func (*RawScanResponse) Descriptor() ([]byte, []int) {
	return file_rawkv_proto_rawDescGZIP(), []int{8}
}

func (x *RawScanResponse) GetKvs() []*KvPair {
	if x != nil {
		return x.Kvs
	}
	return nil
}

var File_rawkv_proto protoreflect.FileDescriptor

const file_rawkv_proto_rawDesc = "" +
	"\n" +
	"\vrawkv.proto\x12\x05rawkv\"1\n" +
	"\rRawGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x0e\n" +
	"\x02cf\x18\x02 \x01(\tR\x02cf\"C\n" +
	"\x0eRawGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1b\n" +
	"\tnot_found\x18\x02 \x01(\bR\bnotFound\"G\n" +
	"\rRawPutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x0e\n" +
	"\x02cf\x18\x03 \x01(\tR\x02cf\"\x10\n" +
	"\x0eRawPutResponse\"4\n" +
	"\x10RawDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x0e\n" +
	"\x02cf\x18\x02 \x01(\tR\x02cf\"\x13\n" +
	"\x11RawDeleteResponse\"S\n" +
	"\x0eRawScanRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x0e\n" +
	"\x02cf\x18\x03 \x01(\tR\x02cf\"0\n" +
	"\x06KvPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"2\n" +
	"\x0fRawScanResponse\x12\x1f\n" +
	"\x03kvs\x18\x01 \x03(\v2\r.rawkv.KvPairR\x03kvs2\xef\x01\n" +
	"\x05RawKV\x125\n" +
	"\x06RawGet\x12\x14.rawkv.RawGetRequest\x1a\x15.rawkv.RawGetResponse\x125\n" +
	"\x06RawPut\x12\x14.rawkv.RawPutRequest\x1a\x15.rawkv.RawPutResponse\x12>\n" +
	"\tRawDelete\x12\x17.rawkv.RawDeleteRequest\x1a\x18.rawkv.RawDeleteResponse\x128\n" +
	"\aRawScan\x12\x15.rawkv.RawScanRequest\x1a\x16.rawkv.RawScanResponseB7Z5github.com/llllleeeewwwiis/standalone/proto/pkg/rawkvb\x06proto3"

var (
	file_rawkv_proto_rawDescOnce sync.Once
	file_rawkv_proto_rawDescData []byte
)

func file_rawkv_proto_rawDescGZIP() []byte {
	file_rawkv_proto_rawDescOnce.Do(func() {
		file_rawkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rawkv_proto_rawDesc), len(file_rawkv_proto_rawDesc)))
	})
	return file_rawkv_proto_rawDescData
}

var file_rawkv_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rawkv_proto_goTypes = []any{
	(*RawGetRequest)(nil),     // 0: rawkv.RawGetRequest
	(*RawGetResponse)(nil),    // 1: rawkv.RawGetResponse
	(*RawPutRequest)(nil),     // 2: rawkv.RawPutRequest
	(*RawPutResponse)(nil),    // 3: rawkv.RawPutResponse
	(*RawDeleteRequest)(nil),  // 4: rawkv.RawDeleteRequest
	(*RawDeleteResponse)(nil), // 5: rawkv.RawDeleteResponse
	(*RawScanRequest)(nil),    // 6: rawkv.RawScanRequest
	(*KvPair)(nil),            // 7: rawkv.KvPair
	(*RawScanResponse)(nil),   // 8: rawkv.RawScanResponse
}
var file_rawkv_proto_depIdxs = []int32{
	7, // 0: rawkv.RawScanResponse.kvs:type_name -> rawkv.KvPair
	0, // 1: rawkv.RawKV.RawGet:input_type -> rawkv.RawGetRequest
	2, // 2: rawkv.RawKV.RawPut:input_type -> rawkv.RawPutRequest
	4, // 3: rawkv.RawKV.RawDelete:input_type -> rawkv.RawDeleteRequest
	6, // 4: rawkv.RawKV.RawScan:input_type -> rawkv.RawScanRequest
	1, // 5: rawkv.RawKV.RawGet:output_type -> rawkv.RawGetResponse
	3, // 6: rawkv.RawKV.RawPut:output_type -> rawkv.RawPutResponse
	5, // 7: rawkv.RawKV.RawDelete:output_type -> rawkv.RawDeleteResponse
	8, // 8: rawkv.RawKV.RawScan:output_type -> rawkv.RawScanResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rawkv_proto_init() }
func file_rawkv_proto_init() {
	if File_rawkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rawkv_proto_rawDesc), len(file_rawkv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rawkv_proto_goTypes,
		DependencyIndexes: file_rawkv_proto_depIdxs,
		MessageInfos:      file_rawkv_proto_msgTypes,
	}.Build()
	File_rawkv_proto = out.File
	file_rawkv_proto_goTypes = nil
	file_rawkv_proto_depIdxs = nil
}
