// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: rawkv.proto

package rawkv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RawKV_RawGet_FullMethodName    = "/rawkv.RawKV/RawGet"
	RawKV_RawPut_FullMethodName    = "/rawkv.RawKV/RawPut"
	RawKV_RawDelete_FullMethodName = "/rawkv.RawKV/RawDelete"
	RawKV_RawScan_FullMethodName   = "/rawkv.RawKV/RawScan"
)

// RawKVClient is the client API for RawKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RawKVClient interface {
	RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error)
	RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error)
	RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error)
	RawScan(ctx context.Context, in *RawScanRequest, opts ...grpc.CallOption) (*RawScanResponse, error)
}

type rawKVClient struct {
	cc grpc.ClientConnInterface
}

func NewRawKVClient(cc grpc.ClientConnInterface) RawKVClient {
	return &rawKVClient{cc}
}

func (c *rawKVClient) RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawGetResponse)
	err := c.cc.Invoke(ctx, RawKV_RawGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rawKVClient) RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawPutResponse)
	err := c.cc.Invoke(ctx, RawKV_RawPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rawKVClient) RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawDeleteResponse)
	err := c.cc.Invoke(ctx, RawKV_RawDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rawKVClient) RawScan(ctx context.Context, in *RawScanRequest, opts ...grpc.CallOption) (*RawScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawScanResponse)
	err := c.cc.Invoke(ctx, RawKV_RawScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RawKVServer is the server API for RawKV service.
// All implementations must embed UnimplementedRawKVServer
// for forward compatibility.
type RawKVServer interface {
	RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error)
	RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error)
	RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error)
	RawScan(context.Context, *RawScanRequest) (*RawScanResponse, error)
	mustEmbedUnimplementedRawKVServer()
}

// UnimplementedRawKVServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRawKVServer struct{}

func (UnimplementedRawKVServer) RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawGet not implemented")
}
func (UnimplementedRawKVServer) RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawPut not implemented")
}
func (UnimplementedRawKVServer) RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawDelete not implemented")
}
func (UnimplementedRawKVServer) RawScan(context.Context, *RawScanRequest) (*RawScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawScan not implemented")
}
func (UnimplementedRawKVServer) mustEmbedUnimplementedRawKVServer() {}
func (UnimplementedRawKVServer) testEmbeddedByValue()               {}

// UnsafeRawKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RawKVServer will
// result in compilation errors.
type UnsafeRawKVServer interface {
	mustEmbedUnimplementedRawKVServer()
}

func RegisterRawKVServer(s grpc.ServiceRegistrar, srv RawKVServer) {
	// If the following call pancis, it indicates UnimplementedRawKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RawKV_ServiceDesc, srv)
}

func _RawKV_RawGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RawKVServer).RawGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RawKV_RawGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RawKVServer).RawGet(ctx, req.(*RawGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RawKV_RawPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RawKVServer).RawPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RawKV_RawPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RawKVServer).RawPut(ctx, req.(*RawPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RawKV_RawDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RawKVServer).RawDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RawKV_RawDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RawKVServer).RawDelete(ctx, req.(*RawDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RawKV_RawScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RawKVServer).RawScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RawKV_RawScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RawKVServer).RawScan(ctx, req.(*RawScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RawKV_ServiceDesc is the grpc.ServiceDesc for RawKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RawKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rawkv.RawKV",
	HandlerType: (*RawKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawGet",
			Handler:    _RawKV_RawGet_Handler,
		},
		{
			MethodName: "RawPut",
			Handler:    _RawKV_RawPut_Handler,
		},
		{
			MethodName: "RawDelete",
			Handler:    _RawKV_RawDelete_Handler,
		},
		{
			MethodName: "RawScan",
			Handler:    _RawKV_RawScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rawkv.proto",
}
